### ISSUE TITLE
Application ads on Facebook 

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#1]
Please use this issue to post ideas for text (in English, Arabic, or both) to use when advertising the application on Facebook.

**Comment by rebeccaradding** [comment]
For example:

---

Want to learn to code? Our intensive course in full stack JavaScript will prepare you for a job in web development in just 16 weeks. 

Study in English in this international program supported by the UK Israel Tech Hub.

Apply now: www.foundersandcoders.com

**Comment by esraajb** [comment]
Help

**Comment by mattlub** [comment]
Interested in web development? Be one of the next group of students on our 16-week, intensive Javascript course! Find out more and apply now at www.foundersandcoders.com!

**Comment by sofer** [comment]
I am not sure if this issue is still live, but I would probably emphasise that this is for people wanting a *career in web development* ("interest" may not send a strong enough message), that it is *an international programme taught in English* and that we are *offering scholarships* (is that disingenuous? I am not sure that describing the course as *free* is helpful).
