### ISSUE TITLE
Coding for everyone events

### ISSUE THREAD

**Issue by matthewdking** [foundersandcoders/nazareth-social-media#19]
Me and @paulhanna1933 are looking into sharing the event for coding for everyone on Mondays.

I was just wondering if there are any guidelines for this? Should I create the event or can someone with access to the FAC facebook page create it? Are there any predetermined pages where we can share the event that have proved successful in the past? Maybe we can ask people in the coding for everyone gitter channel to share the event with their friends?

**Comment by rebeccaradding** [comment]
@matthewdking @paulhanna1933 great questions. We definitely need guidelines for creating Coding for Everyone events and lists of groups to share them with. If and when we have budget, it may also make sense to create events on Meetup.com (which requires a monthly subscription fee).

As a starting point:
- Draft a description for a weekly event (take a look at past events)
- Create a list of groups/pages/influencers we can share it with on a regular basis (you will need to cultivate a relationship with the group/page admin, or they might not approve the posts in a timely fashion)

I suggest tackling these two items next week, and opening an issue in `nazareth-outreach`, as I think it will get more visibility from others there (I'm rethinking having a `social-media` repo). 

Once we have consensus on the shape of the weekly event description, and a plan for promoting, I'm happy to make one or both of you admins of the FAC Nazareth page so that you can share the post as the page.

**Comment by rebeccaradding** [comment]
https://github.com/foundersandcoders/nazareth-programme/issues/176
